// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diiukihnpvzkwcyrpsvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpaXVraWhucHZ6a3djeXJwc3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDI2NjksImV4cCI6MjA3Mjk3ODY2OX0.laQF2LeQekpn9E4k03gsLO0pTitqrJ6WwdmUQzWr5UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});