// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cblzhhqohkzhvrlacctr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibHpoaHFvaGt6aHZybGFjY3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDM5ODIsImV4cCI6MjA3MzU3OTk4Mn0.Krc39vEoKlOrKSt5KWW3en1N7PZXxaVHA2YL6JP4yyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});